version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    image: sainath2236/online-docs-app-server
    restart: always
    ports:
      - "8080:8080"
    links:
      - "mongo"
    environment:
      WAIT_HOSTS: mongo:27017
  client:
    image: sainath2236/online-docs-app-client
    restart: always
    ports:
      - "3000:3000"
    links:
      - "app"
    environment:
      REACT_APP_SERVER: ${REACT_APP_SERVER}
  nginx:
    image: sainath2236/online-docs-app-nginx
    ports:
      - '80:80' 
    links: 
      - client
      - app
